### ISSUE TITLE
chrome: using background: rgba(/*[[custom-scrollbar-color]]*/, .8) for customizing is broken

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/Overlay-Scrollbars#1]
Not sure what the problem is but using it doesnt work on any chrome based browsers I tested.

**Comment by Mottie** [comment]
It's for Firefox only - https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color#Browser_compatibility

**Comment by Mottie** [comment]
Oh, I misread that...

I think it might be easier to replace the placeholder with a css variable:



```css
:root {
  --custom-scrollbar-color: /*[[custom-scrollbar-color]]*/;
}

body {
  background: rgba(var(--custom-scrollbar-color), .8) !important;
}
```

This is what I did with the [wikipedia style](https://github.com/StylishThemes/Wikipedia-Dark/blob/master/wikipedia-dark.user.css) - it might be better this way, that way users that install our style on cascadea only need to create a new style with the `:root` definitions.

**Comment by the-j0k3r** [comment]
I was trying that a few moments ago in between other things, I think that didnt work either, but let me give it another go in a sec, thx =)

**Comment by the-j0k3r** [comment]
```css
:root {
  --custom-scrollbar-color: /*[[custom-scrollbar-color]]*/;
}
body {
  background: rgba(var(--custom-scrollbar-color), .8) !important;
}
```

Edit:
for some reason chrome and some friends dont like this either =( makes no sense :(


```css
/* ==UserStyle==
@name        Global Overlay Scrollbars
@version     1.0.2
@description Global overlay scrollbars
@namespace   StylishThemes
@author      StylishThemes
+co-authors  https://github.com/StylishThemes/Overlay-Scrollbars/graphs/contributors
@homepageURL https://github.com/StylishThemes/Overlay-Scrollbars
@supportURL  https://github.com/StylishThemes/Overlay-Scrollbars/issues
@updateURL   https://raw.githubusercontent.com/StylishThemes/Overlay-Scrollbars/master/global-overlay-scrollbars.user.css
@license     CC-BY-SA-4.0
@advanced color custom-scrollbar-color "Scrollbar thumb color" rgba(140, 140, 140, .5)
@advanced color custom-track-color "Track color" transparent
@advanced text webkit-scrollbar-width-height "Webkit scrollbar width/height" 5px
==/UserStyle== */
:root {
	--webkit-scrollbar-hover: /*[[custom-scrollbar-color]]*/;
}
* {
  scrollbar-color: /*[[custom-scrollbar-color]]*/ /*[[custom-track-color]]*/ !important;
  scrollbar-width: thin !important;
}
/* Chrome and derivatives*/
::-webkit-scrollbar {
  max-width: /*[[webkit-scrollbar-width-height]]*/ !important;
  max-height: /*[[webkit-scrollbar-width-height]]*/ !important;
  background: /*[[custom-track-color]]*/ !important;
}
::-webkit-scrollbar-track, ::-webkit-scrollbar-corner,
::-webkit-scrollbar-track-piece {
  background: /*[[custom-track-color]]*/ !important;
}
::-webkit-scrollbar-thumb {
  background: /*[[custom-scrollbar-color]]*/ !important;
}
::-webkit-scrollbar-thumb:hover {
  background: rgba(var(--webkit-scrollbar-hover), .8) !important;
}
```

No lice, I mean dice.

**Comment by Mottie** [comment]
Try this:


```css
/* ==UserStyle==
@name        GitHub Overlay Scrollbars
@version     1.0.2
@description GitHub overlay scrollbars
@namespace   StylishThemes
@author      StylishThemes
+co-authors  https://github.com/StylishThemes/Overlay-Scrollbars/graphs/contributors
@homepageURL https://github.com/StylishThemes/Overlay-Scrollbars
@supportURL  https://github.com/StylishThemes/Overlay-Scrollbars/issues
@updateURL   https://raw.githubusercontent.com/StylishThemes/Overlay-Scrollbars/master/github-overlay-scrollbars.user.css
@license     CC-BY-SA-4.0
@advanced color custom-scrollbar-color "Scrollbar thumb color" rgba(140, 140, 140, .5)
@advanced color webkit-scrollbar-hover "Webkit thumb hover" rgba(79, 140, 201, .8)
@advanced color custom-track-color "Track color" transparent
@advanced text webkit-scrollbar-width-height "Webkit scrollbar width/height" 5px
@preprocessor uso
==/UserStyle== */
/* Firefox and derivatives >= v64*/
@-moz-document regexp("^https?://((gist|guides|help|launch-editor|raw|resources|status|developer)\\.)?github\\.com/((?!generated_pages/preview).)*$"),
domain("githubusercontent.com"),
domain("graphql-explorer.githubapp.com") {
  :root {
    --webkit-scrollbar-width-height: /*[[webkit-scrollbar-width-height]]*/;
    --custom-track-color: /*[[custom-track-color]]*/;
    --custom-scrollbar-color: /*[[custom-scrollbar-color]]*/;
    --webkit-scrollbar-hover: rgba(/*[[webkit-scrollbar-hover-rgb]]*/, .8);
  }
  * {
    scrollbar-color: var(--custom-scrollbar-color) var(--custom-track-color) !important;
    scrollbar-width: thin !important;
  }
  /* Chrome and derivatives*/
  ::-webkit-scrollbar {
    max-width: var(--webkit-scrollbar-width-height) !important;
    max-height: var(--webkit-scrollbar-width-height) !important;
    background: var(--custom-track-color) !important;
  }
  ::-webkit-scrollbar-track,
  ::-webkit-scrollbar-corner,
  ::-webkit-scrollbar-track-piece {
    background: var(--custom-track-color) !important;
  }
  ::-webkit-scrollbar-thumb {
    background: var(--custom-scrollbar-color) !important;
  }
  ::-webkit-scrollbar-thumb:hover {
    background: var(--webkit-scrollbar-hover) !important;
  }
}
```

**Comment by the-j0k3r** [comment]
That works, but here is the catch, the whole point here is to only have two main color picker track and thumb, then the hover would be just the ` rgba(/*[[custom-scrollbar-color]]*/, .8);`,

I wanted to do away with the hover color selector `@advanced color webkit-scrollbar-hover "Webkit thumb hover" rgba(140, 140, 140, .5)`, and that crumbling makes no sense to this cookie. =(

i.e. not


```
--webkit-scrollbar-hover: rgba(/*[[webkit-scrollbar-hover-rgb]]*/, .8);
```
instead use
```
--webkit-scrollbar-hover: rgba(/*[[custom-scrollbar-color]]*/, .8);
```
That doesnt work at all chrome side and why not idk, and if it doesnt then theres no point to that


try this, you will see that the hover color is using fallback and not the user selected color.
```
/* ==UserStyle==
@name        Global Overlay Scrollbars
@version     1.0.2
@description Global overlay scrollbars
@namespace   StylishThemes
@author      StylishThemes
+co-authors  https://github.com/StylishThemes/Overlay-Scrollbars/graphs/contributors
@homepageURL https://github.com/StylishThemes/Overlay-Scrollbars
@supportURL  https://github.com/StylishThemes/Overlay-Scrollbars/issues
@updateURL   https://raw.githubusercontent.com/StylishThemes/Overlay-Scrollbars/master/global-overlay-scrollbars.user.css
@license     CC-BY-SA-4.0

@preprocessor uso

@advanced color custom-scrollbar-color "Scrollbar thumb color" rgba(140, 140, 140, .5)
@advanced color custom-track-color "Track color" transparent
@advanced text webkit-scrollbar-width-height "Webkit scrollbar width/height" 5px
==/UserStyle== */
:root {
  --webkit-scrollbar-width-height: /*[[webkit-scrollbar-width-height]]*/;
  --custom-track-color: /*[[custom-track-color]]*/;
  --custom-scrollbar-color: /*[[custom-scrollbar-color]]*/;
  --webkit-scrollbar-hover: rgba(/*[[custom-scrollbar-color]]*/, .8);
}
* {
  scrollbar-color: var(--custom-scrollbar-color) var(--custom-track-color) !important;
  scrollbar-width: thin !important;
}
/* Chrome and derivatives*/
::-webkit-scrollbar {
  max-width: var(--webkit-scrollbar-width-height) !important;
  max-height: var(--webkit-scrollbar-width-height) !important;
  background: var(--custom-track-color) !important;
}
::-webkit-scrollbar-track,
::-webkit-scrollbar-corner,
::-webkit-scrollbar-track-piece {
  background: var(--custom-track-color) !important;
}
::-webkit-scrollbar-thumb {
  background: var(--custom-scrollbar-color) !important;
}
::-webkit-scrollbar-thumb:hover {
  background: var(--webkit-scrollbar-hover) !important;
}
```

**Comment by the-j0k3r** [comment]
also

```
  max-width: var(--webkit-scrollbar-width-height) !important;
  max-height: var(--webkit-scrollbar-width-height) !important;
```

are completely ignored, so seems I hate scrollbars now.

**Comment by Mottie** [comment]
It's not working because it needs the `-rgb` at the end of the placeholder.

```
--webkit-scrollbar-hover: rgba(/*[[custom-scrollbar-color-rgb]]*/, .8);
```

**Comment by the-j0k3r** [comment]
I cant get it to work like that either. The hover is instead the fallbak and not a rgba representation

```css
/* ==UserStyle==
@name        Global Overlay Scrollbars
@version     1.0.3
@description Global overlay scrollbars
@namespace   StylishThemes
@author      StylishThemes
+co-authors  https://github.com/StylishThemes/Overlay-Scrollbars/graphs/contributors
@homepageURL https://github.com/StylishThemes/Overlay-Scrollbars
@supportURL  https://github.com/StylishThemes/Overlay-Scrollbars/issues
@updateURL   https://raw.githubusercontent.com/StylishThemes/Overlay-Scrollbars/master/global-overlay-scrollbars.user.css
@license     CC-BY-SA-4.0
@preprocessor uso
@advanced color custom-scrollbar-color        "Scrollbar thumb color" rgba(140, 140, 140, .5)
@advanced color custom-track-color            "Scrollbar track color" transparent
@advanced text webkit-scrollbar-width-height  "Webkit scrollbar width/height" 6px
@advanced text webkit-scrollbar-border-radius "Webkit scrollbar border radius" 1px
==/UserStyle== */
:root {
  --custom-track-color: /*[[custom-track-color]]*/;
  --custom-scrollbar-color: /*[[custom-scrollbar-color]]*/;
  --webkit-scrollbar-hover: rgba(/*[[custom-scrollbar-color-rgb]]*/), .8;
  --webkit-scrollbar-width-height: /*[[webkit-scrollbar-width-height]]*/;
  --webkit-scrollbar-border-radius: /*[[webkit-scrollbar-border-radius]]*/;
}
* {
  scrollbar-color: var(--custom-scrollbar-color) var(--custom-track-color) !important;
  scrollbar-width: thin !important;
}
/* Chrome and derivatives*/
::-webkit-scrollbar {
  max-width: var(--webkit-scrollbar-width-height) !important;
  max-height: var(--webkit-scrollbar-width-height) !important;
  background: var(--custom-track-color) !important;
}
::-webkit-scrollbar-corner,
::-webkit-scrollbar-track,
::-webkit-scrollbar-track-piece {
  background: var(--custom-track-color) !important;
}
::-webkit-scrollbar-thumb {
  background: var(--custom-scrollbar-color) !important;
  border-radius: var(--webkit-scrollbar-border-radius) !important;
}
::-webkit-scrollbar-thumb:hover {
  background: var(--webkit-scrollbar-hover) !important;
}
```
