### ISSUE TITLE
Make the scrollbar offset X amount from the edge of the page

### ISSUE THREAD

**Issue by NVHT** [StylishThemes/Overlay-Scrollbars#13]
**Describe the change you'd like**
![image](https://user-images.githubusercontent.com/8341213/208084865-cdbba216-43de-49ca-980e-17c9cd52eb1b.png)
This is the original css.
![image](https://user-images.githubusercontent.com/8341213/208084616-1dad3b7a-a12a-485c-a18a-b23ce0af91a2.png)
This is what I want.
**Additional context**

**Comment by silverwind** [comment]
Does this CSS work for you (replacing the userstyle completely)?

```css
@supports (overflow: overlay) {
  body {
    overflow: overlay;
    scrollbar-gutter: stable;
  }
}
```
