### ISSUE TITLE
Overlays on top of a Youtube video

### ISSUE THREAD

**Issue by RomanKornev** [StylishThemes/Overlay-Scrollbars#6]
When playing a Youtube video in fullscreen, I can see the scrollbar on the right at all times.
Is there any way of applying the style only if it's not in fullscreen?
I tried disabling it, but then it's just a default scrollbar everywhere on Youtube.

Windows 10 x64, Chrome 71.

**Comment by the-j0k3r** [comment]
Hi and thank you for reporting this.

can you try adding this into style.


```css
:fullscreen {
  overflow: hidden !important;
}
```

If it works let me know. thx =)

**Comment by RomanKornev** [comment]
No, that does not fix it. Nothing changes if I do that.

**Comment by the-j0k3r** [comment]
Thanks you, I thought Chrome would accept that, clearly not, What about

```css
:-webkit-full-screen {
  overflow: hidden !important;
}
```
