### ISSUE TITLE
All scrollbars can be set mousehover

### ISSUE THREAD

**Issue by ghost** [StylishThemes/Overlay-Scrollbars#9]
**Describe the change you'd like**
I've already set all scrollbars of height is 3px. but I really dislike to see a line . Bcz I like clean layout, and if all scrollbars are hidden, sometimes I need to know how much rest of contents by scrollbar height. 
So if all scrollbar can be set mousehover , it will be nice fit 2 cases ,for looks clean and for know how much rest of contents. 

I don't how to code ,try it but failed. 
**Additional context**
Thanks so much !

**Comment by the-j0k3r** [comment]
Thanks for reaching out with this request.

As far as I know there is mouseover for all scrollbars So I dont understand what exactly you are asking for.

I also notice that the language may be a barrier, so try to use screenshots or gif demos of the issue to illustrate what the issue is.

Also please provide browser details.

**Comment by ghost** [comment]
Like this : 
![ISoc1mILGh](https://user-images.githubusercontent.com/16850883/77824553-80246000-713e-11ea-9b1b-b25ab919fe8e.gif)

I want to covert all non-mousehover scrollbars into mousehover style. and original mousehover scrollbar is stay. 

I donno is it possible ? 

Thank you .

**Comment by the-j0k3r** [comment]
So you only want to see the scrollbars on mouseover and not all the time?

If so, Ill have a look if this can be integrated.

**Comment by ghost** [comment]
Yes. that's right. 
Okay. Thanks so much ! 
I tried it ,but failed.  
Waiting for your good news. 

Oh just for chrome, I don't care others.

**Comment by ghost** [comment]
I thought another solution for my case. **fully transparent scrollbar.** 
But didn't work, is it a bug ? 
![image](https://user-images.githubusercontent.com/16850883/77843209-7e55ad80-71cd-11ea-8b86-85e05fa8d09f.png)

Scrollbar thumb color and track color of transparent values are **0**. but still it's colored .

**Comment by Mottie** [comment]
Hi @steveyang331!

I just added a "Scrollbar thumb hover color" to the style. Please see if that works for you.

**Comment by Mottie** [comment]
Hmm, maybe I should have named it webkit hover color... since it only works in webkit browsers.

**Comment by ghost** [comment]
The scorllbars didn't hide ?? in Chrome 

Sorry . it works. 

I realized that it need to disable and re-enable style file again.

**Comment by the-j0k3r** [comment]
1) Ignore those linting errors

2) It works setting the thumb to transparent and whatever color you want

>Hmm, maybe I should have named it webkit hover color... since it only works in webkit browsers.

You can, but the label will wrap.

@Mottie 

It would be nice if we could have sections but we cant simply add an empty label to the popup

So like
```
@var label firefox "Firefox settings"
@var color foo "bar" #f3f
@var label webkit "Webkit settings"
@var color foo "bar" #f3f
```

**Comment by ghost** [comment]
Sorry . it works.

I realized that it need to disable and enable style file again.

**Comment by the-j0k3r** [comment]
> I realized that it need to disable and enable style file again.

Yes, you cant have the style open for editing and change settings without disabling/reenabling the style, else the settings dont apply.

**Comment by ghost** [comment]
Thank you so much @the-j0k3r  and @Mottie .

I set 3 colors to `#FFF0 `

Please also enjoy my idea.  All website scrollbars are hidden and transparent , you also can click the scrollbar tack area to quick scroll down and scroll page . The world is so clear without boundary.

**Comment by the-j0k3r** [comment]
@Mottie we cant do this in Firefox it seems adding hover property to Firefox makes the scrollbars all gray.

Edit: also I think an alternatively instead of adding a long label to swatch for webkit is to move the swatch to after the webkit width/height.

**Comment by Mottie** [comment]
Yeah, Firefox doesn't handle the hover, so that why I said it's webkit only.

> move the swatch to after the webkit width/height.

Yes, please modify it as you wish... you probably use this style more than I do.

**Comment by ghost** [comment]
I think it can be add tack hover color.
@Mottie added thumb hover color. 
I'm going to try it myself, if no work, I'll request your help .
Thanks.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/16850883/77824553-80246000-713e-11ea-9b1b-b25ab919fe8e.gif)
Please look at this gif again. **the track and thumb can be hover the same time.** 
**Sorry I didn't notice about track before.** 

I add track hover setting, it can be set color ,but didn't work for track hover. 

`@advanced color custom-track-color-hover  "Scrollbar track hover color" rgba(79, 140, 201, .8)"`
```
--webkit-scrollbar-thumb-hover: rgb(/*[[custom-thumb-color-hover-rgb]]*/
	);
--webkit-scrollbar-track-hover: rgb(/*[[custom-track-color-hover]]*/
	);
```
```
::-webkit-scrollbar-thumb:hover { background: var(--webkit-scrollbar-thumb-hover) !important; }  
::-webkit-scrollbar-track:hover { background: var(--webkit-scrollbar-track-hover) !important; }
```

**Comment by the-j0k3r** [comment]
Thats either a bug or not supported, its unrelated to this style.

Thats is a complain to google ; wink wink


```css
/* ==UserStyle==
@name        Global Overlay Scrollbars
@version     2.0.0
@description Global overlay scrollbars
@namespace   StylishThemes
@author      StylishThemes
+co-authors  https://github.com/StylishThemes/Overlay-Scrollbars/graphs/contributors
@homepageURL https://github.com/StylishThemes/Overlay-Scrollbars
@supportURL  https://github.com/StylishThemes/Overlay-Scrollbars/issues
@updateURL   https://raw.githubusercontent.com/StylishThemes/Overlay-Scrollbars/master/global-overlay-scrollbars.user.css
@license     CC-BY-SA-4.0
@preprocessor uso
@advanced color custom-thumb-color            "Scrollbar thumb color" rgba(79, 140, 201, .6)
@advanced color custom-track-color            "Scrollbar track color" transparent
@advanced dropdown custom-width               "Scrollbar track width/height" {
  thin "Firefox Thin" <<<EOT
  thin EOT;
  auto "Firefox Auto" <<<EOT
  auto EOT;
  none "Firefox None" <<<EOT
  none EOT;
}
@advanced color custom-thumb-color-hover      "Webkit scrollbar thumb hover color" rgba(79, 140, 201, .8)
@advanced color custom-track-color-hover      "Webkit Scrollbar track hover color" transparent
@advanced text webkit-scrollbar-width-height  "Webkit scrollbar width/height" 6px
@advanced text webkit-scrollbar-border-radius "Webkit scrollbar border radius" 0px
@advanced checkbox workaround-gh-scrollbars   "Enable GitHub workaround scrollbars" 0 {
  Enabled "Enabled" <<<EOT
  /* GitHub https://github.com/StylishThemes/GitHub-Dark/issues/870 *\/
  .integrations-select-repos::-webkit-scrollbar {
    max-width: var(--webkit-scrollbar-width-height) !important;
    width: var(--webkit-scrollbar-width-height) !important;
  }
  .integrations-select-repos::-webkit-scrollbar-thumb {
    background: var(--custom-thumb-color) !important;
    border: 0 !important;
    border-radius: var(--webkit-scrollbar-border-radius) !important;
    box-shadow: none !important;
  }
  .integrations-select-repos::-webkit-scrollbar-track-piece {
    background: var(--custom-track-color) !important;
  } EOT;
  disabled "Disabled" <<<EOT
  disabled EOT;
}
==/UserStyle== */
:root {
  --custom-track-color: /*[[custom-track-color]]*/;
  --custom-thumb-color: /*[[custom-thumb-color]]*/;
  --custom-width: /*[[custom-width]]*/;
  --webkit-scrollbar-hover: rgb(/*[[custom-thumb-color-hover-rgb]]*/);
  --webkit-scrollbar-track-hover: /*[[custom-track-color-hover-rgb]]*/;
  --webkit-scrollbar-width-height: /*[[webkit-scrollbar-width-height]]*/;
  --webkit-scrollbar-border-radius: /*[[webkit-scrollbar-border-radius]]*/;
}
*:not(select) {
  scrollbar-color: var(--custom-thumb-color) var(--custom-track-color) !important;
  scrollbar-width: var(--custom-width) !important;
}
/* Chrome and derivatives*/
::-webkit-scrollbar {
  max-width: var(--webkit-scrollbar-width-height) !important;
  max-height: var(--webkit-scrollbar-width-height) !important;
  background: var(--custom-track-color) !important;
}
::-webkit-scrollbar-corner,
::-webkit-scrollbar-track,
::-webkit-scrollbar-track-piece {
  background: var(--custom-track-color) !important;
}
::-webkit-scrollbar-thumb {
  background: var(--custom-thumb-color) !important;
  border-radius: var(--webkit-scrollbar-border-radius) !important;
}
::-webkit-scrollbar-corner:hover,
::-webkit-scrollbar-track:hover,
::-webkit-scrollbar-track-piece:hover {
  background: var(--webkit-scrollbar-track-hover) !important;
}
::-webkit-scrollbar-thumb:hover {
  background: var(--webkit-scrollbar-hover) !important;
}

```
